---
title: "R Notebook"
output: html_notebook
---

Make figures for the DSFbase paper

```{r}
library(tidyverse)
library(extrafont)
```

Read combined dsfbase files
```{r}
id_map <- read_rds("../03_combined_data/dsfbase_id_map.rds")
dsfbase <- read_rds("../03_combined_data/dsfbase.rds")
```

DSFbase theme
```{r}
dsfbase <- dsfbase |> 
  mutate(major_subset = factor(case_when(subset == "SYPRO_canon" ~ "canon",
                                  subset == "SYPRO_noncanon" ~ "noncanon",
                                  .default = subset
                                  ), levels = c("canon", "noncanon", "gotcha")))

dsfbase$major_subset |> table()
```

Plot all traces
```{r}
p_basic <- 
  dsfbase |> 
  ggplot(aes(x = Temperature, 
             y = value_norm, 
             group = id,
             alpha = major_subset)) +
  geom_line(linewidth = 0.1) +
  scale_alpha_manual(values = c("canon" = 0.05,
                                "noncanon" = 0.05,
                                "gotcha" = 0.2)) +
  facet_wrap(~major_subset,
             scales = "free",
             labeller = labeller(major_subset = str_to_title)) +
  scale_x_continuous(breaks = seq(25, 95, by = 10)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  hrbrthemes::theme_ipsum(base_size = 10) +
  theme(aspect.ratio = 1,
        legend.position = "none",
        plot.background = element_rect(fill = "transparent")) +
  labs(x = "Temperature (ºC)",
       y = "Normalized RFU")

ggsave("../04_plots/draft_plots/dsfbase_glance.pdf", 
       p_basic, 
       width = 7,
       height = 3,
       device = cairo_pdf,
       bg = "transparent")
```